#!/usr/bin/env ruby
require_relative 'moodledocker-common.rb'
require 'fileutils'

def start_psql()
  currentpath = Dir.pwd + "/."

  projectname =  MoodleDocker.project_name(currentpath)
  if projectname == nil
    puts "Error: For this folder no Docker instance could be found."
    return false
  end

  path = "#{MoodleDocker.base_dir}/#{projectname}"
  FileUtils.cd(path) do
    postgresinterface = `docker-compose port db 5432`
    postgresport = postgresinterface.split(":")[1].strip
  end

  puts "Starting psql for #{projectname}"
#  set PGPASSWORD=hello
  system "PGPASSWORD=hello psql -p #{postgresport} -h localhost -U testdb"

  return true
end


if ARGV.length != 0 then
  puts "Usage: moodledocker-psql"
  exit
end

if !start_psql() then
  exit!
end

