#!/usr/bin/env ruby
require_relative 'moodledocker-common.rb'
require 'fileutils'

def create_if_empty(name, srcdir)
  if !MoodleDocker.name_valid? (name)
    return false
  end

  if !File.directory?(srcdir)
    puts "Error: Source directory \"#{srcdir}\" does not exist."
    return false
  end

  if MoodleDocker.project_exists?(name)
    puts "  Error: Project directory \"#{name}\" already exists."
    return false
  end

  MoodleDocker.build_yaml(name, srcdir)

  puts "Done."
  puts "Docker project directory for \"#{name}\" is now at: #{MoodleDocker.base_dir}/#{name}"
  puts "Start containers using: moodledocker control #{name} up"
  return true
end


if ARGV.length != 2 then
  puts "Usage: moodledocker-create NAME SRCDIR"
  exit
end

if !create_if_empty(ARGV[0], ARGV[1]) then
  exit!
end

