#!/usr/bin/env ruby
require_relative 'moodledocker-common.rb'
require 'fileutils'
require 'erb'

def start_behat(name)
  if !MoodleDocker.name_valid? (name)
    return false
  end

  if !MoodleDocker.project_exists?(name)
    puts "  Error: Project directory \"#{name}\" does not exist."
    return false
  end
  puts "Checking if seleniumserver is running"
  seleniumserver = `docker ps -f name=seleniumserver -q`
  if (seleniumserver.strip == "")
     seleniumserver= `docker ps -a -f name=seleniumserver -q`
     if (seleniumserver.strip == "")
          puts "There is no container with name seleniumserver"
     	  puts "Make sure you downloaded the correct container and execute something like:"
	  puts "docker run --name seleniumserver -d -p 4444:4444 selenium/standalone-firefox:2.53.1-beryllium"
	  return false
     else
          print "Starting selenium server"
          `docker start seleniumserver`
          puts " ... done"
     end
  end

  puts "Starting webserver"
  system "docker exec -it #{name.gsub("_","")}_php_1 bash -c 'php -S 0.0.0.0:80 -t /var/www/public'"
  puts " ... done"
  puts "Behat environment is now running"
  
  return true
end


if ARGV.length != 1 then
  puts "Usage: moodledocker-startbehat NAME"
  exit
end

if !start_behat(ARGV[0]) then
  exit!
end

