#!/usr/bin/env ruby
require_relative 'moodledocker-common.rb'
require 'fileutils'

def refresh_if_not_empty(name)
  if !MoodleDocker.name_valid? (name)
    return false
  end

  if !MoodleDocker.project_exists?(name)
    puts "  Error: Project directory \"#{name}\" does not exist."
    return false
  end

  # Make sure everything happens in the *correct* directory!
  MoodleDocker.build_yaml(name, MoodleDocker.base_dir + "/" + name, true)

  puts "Rebuilding images"
  path = "#{MoodleDocker.base_dir}/#{name}"
  FileUtils.cd(path) do
    system "docker-compose build"
  end

  puts "Done."

  return true
end


if ARGV.length != 1 then
  puts "Usage: moodledocker-refresh NAME"
  exit
end

if !refresh_if_not_empty(ARGV[0]) then
  exit!
end

